vscode:
  extensions:
    - vscjava.vscode-maven@0.18.1:Ga0twwGQDu7XhFR1f838vg==
    - vscjava.vscode-java-debug@0.20.0:2XzlrnOFsFzAHrOc51/R6w==
    - vscjava.vscode-java-test@0.19.0:xwfuoJBZpCcLrZ33G3zkXA==